### ISSUE TITLE
Unable to reference exported variables

### ISSUE THREAD

**Issue by Chocobo1** [Wandalen/wretry.action#106]
Here is a minimal workflow to demonstrate the problem:
```yaml
name: test

on: [pull_request, push]

jobs:
  test:
    name: test
    runs-on: ubuntu-latest

    steps:
      - uses: Wandalen/wretry.action@v1
        with:
          command: |
            export ONE=1
            echo "ONE is $ONE"
```

And here is run result:
https://github.com/Chocobo1/test/actions/runs/5524697491/jobs/10077346008#step:3:244

Clearly the expected answer would be `ONE is 1` instead of `ONE is `.

**Comment by dmvict** [comment]
Hello @Chocobo1 

Now I have no time to solve the issue. I will attend to it when I am free. 

Please, use environments context to setup variables:
```yaml 
      - uses: Wandalen/wretry.action@v1
        env: 
           ONE: 1
        with:
```
