### ISSUE TITLE
Retry with value replacement

### ISSUE THREAD

**Issue by mgaitan** [Wandalen/wretry.action#118]
suppose I want to try an action, and if it fails retry changing its inputs. 

```
- uses: Wandalen/wretry.action@master
  with:
    action: owner/action-repo@version
    with: |
      option1: <value>
```
Let's say <value> is "A" in the first attempt, and "B" in the second. 

Is it possible somehow?
