### ISSUE TITLE
Map.pure should have no fields : "key_token"

### ISSUE THREAD

**Issue by dannytsang** [Wandalen/wretry.action#121]
I'm trying to use retry with http request and adding JSON to a the http payload. I get the above error message. Does it mean I cannot have key value pays in my with?

```
deploy:
    name: "Deploy changes"
    needs: [ha-stable-check]
    runs-on: ubuntu-latest
    steps:
      - name: 🔌 Tailscale
        uses: tailscale/github-action@v2
        with:
          authkey: ${{ secrets.TAILSCALE_AUTHKEY }}
      - name: 🚚 Deploying
        uses: Wandalen/wretry.action@master
        with:
          action: fjogeleit/http-request-action@master
          with: |
            url: '${{ secrets.DEPLOYMENT_URL }}'
            method: POST
            customHeaders: '{"Content-Type":"application/json"}'
            data: '{ "key_token":"${{ secrets.PULL_KEY }}" }'
          attempt_limit: 3
          attempt_delay: 2000
```
