### ISSUE TITLE
Getting "Error: Expects non-primitive" when using multiple multiline fields

### ISSUE THREAD

**Issue by darkxeno** [Wandalen/wretry.action#122]
Example inputs used, gathered from github action logs:

```
Wandalen/wretry.action@v1.0.36
  with:
    action: docker/build-push-action@v3
    attempt_limit: 2
    attempt_delay: 2000
    with: file: ./Dockerfile
  tags: ***.dkr.ecr.us-east-1.amazonaws.com/IMAGE_NAME:8771665,***.dkr.ecr.us-east-1.amazonaws.com/IMAGE_NAME:latest
  context: ./.
  load: true
  push: false
  cache-from: type=registry,ref=***.dkr.ecr.us-east-1.amazonaws.com/IMAGE_NAME:latest
  cache-to: type=inline
  ssh: |
    
  build-args: |
    ***
  
  
  env:
    AWS_DEFAULT_REGION: us-east-1
    AWS_REGION: us-east-1
    AWS_ACCESS_KEY_ID: ***
    AWS_SECRET_ACCESS_KEY: ***
    AWS_SESSION_TOKEN: ***
```

Error:
`Error: Expects non-primitive`

The same error happens on the post run step.
```
Post job cleanup.
Post job cleanup.
Post job cleanup.
Error: Expects non-primitive
Post job cleanup.
Logging out of registry ***.dkr.ecr.us-east-1.amazonaws.com
Post job cleanup.
Post job cleanup.
Removing builder
Cleaning up certificates
```

Using the same action [`docker/build-push-action@v3`](https://github.com/docker/build-push-action/blob/fdf7f43ecf7c1a5c7afe936410233728a8c2d9c2/src/context.ts#L60) without "Wandalen/wretry.action@v1.0.36" works as expected.

Any idea about what could be wrong? somehow seem to only be happening with multiline fields.

**Comment by dmvict** [comment]
Hello @darkxeno 

The action is sensible to indentations in `with` input. I believe that the problem is in indentations. Please, replace first part with:
```yaml 
Wandalen/wretry.action@v1.0.36
  with:
    action: docker/build-push-action@v3
    attempt_limit: 2
    attempt_delay: 2000
    file: ./Dockerfile
    tags: ***.dkr.ecr.us-east-1.amazonaws.com/IMAGE_NAME:8771665,***.dkr.ecr.us-east-1.amazonaws.com/IMAGE_NAME:latest
     context: ./.
    load: true
    push: false
    cache-from: type=registry,ref=***.dkr.ecr.us-east-1.amazonaws.com/IMAGE_NAME:latest
    cache-to: type=inline
    ssh: |
    
    build-args: |
      ***
```

Take care about indentations in field `ssh` and `build-args`. Use [example](https://github.com/Wandalen/wretry.action#with) from the documentation, please.

Also, I fixed line `with: file: ./Dockerfile`. Now the line looks like `file: ./Dockerfile`.

**Comment by dmvict** [comment]
Hello @darkxeno 

Yes, the inputs seems to be correct. Please, check that all inputs are singleline or update indentations for multiline inputs. For example, if your build-args input is 
``` 
--arg1 arg
-- arg2 arg
```
Then the input will be formatted as 
```yaml 
build-args: | 
  --arg1 arg
--arg2 arg
``` 

but the actions expects that the second line has same indentation as the first one (or bigger).

**Comment by darkxeno** [comment]
i think i get your point, as we are using | as part of a string, its probably not indenting multiline strings automatically?

the values of build-args is original constructed like this on the input of the custom action:

```
build-_args: |
  ENV_VAR1=value1
  ENV_VAR2=value2
```
and after that provided as the variable ${{ inputs.build_args }} to this action

So you mean if i some force the correct indentation to all lines should be working properly?

**Comment by dmvict** [comment]
Hello @darkxeno 

I think it should work. The best way is to create experimental workflow with public data and hardcoded values.

**Comment by mycarrysun** [comment]
I'm getting the same issue - here is what I'm using in the workflow:

```yaml
    - name: Build image
      uses: Wandalen/wretry.action@v1.3.0
      with:
        action: docker/build-push-action@v3
        with: |
          context: .
          target: ${{ inputs.build-target }}
          file: ${{ inputs.dockerfile }}
```

And here's what shows in the github actions log output as what is being passed to the Wandalen/wretry.action action:
```shell
Run Wandalen/wretry.action@v1.3.0_js_action
  with:
    action: docker/build-push-action@v3
    with: context: .
    target: release
    file: docker/Dockerfile.backend
```

So somehow there is a problem with indentation. I have also tried an extra set of indentation after the first line in the `with` multiline string but got the same result:

```yaml
    - name: Build image
      uses: Wandalen/wretry.action@v1.3.0
      with:
        action: docker/build-push-action@v3
        with: |
          context: .
            target: ${{ inputs.build-target }}
            file: ${{ inputs.dockerfile }}
```

I think there is a bug in the action code somewhere.
