### ISSUE TITLE
feature: remove pre and post actions

### ISSUE THREAD

**Issue by dmvict** [Wandalen/wretry.action#15]
Actual version of action pollute extra workflow steps `pre` and `post`. 

For example. Module [willbe](https://github.com/Wandalen/willbe) uses action `wretry.action`. The step looks like this:
```yaml
    - name : ${{ matrix.node-version }}
      uses : Wandalen/wretry.action@0.2.2
      with :
        action : actions/setup-node@v1
        with : |
          node-version : ${{ matrix.node-version }}
        attempt_limit : 3
        attempt_delay: 1000
```

The action `actions/setup-node@v1` has no `pre` and `post` steps. The workflow has the `pre` and `post` steps for discribed step:
![wilbe_workflow_retry](https://user-images.githubusercontent.com/47529590/133379324-07456937-7e99-433f-938a-26fd82b0d723.png)

So, if the action `wretry.action` will no generate extra steps, then each workflow report will be more clear.
