### ISSUE TITLE
Post-running, regardless of condition

### ISSUE THREAD

**Issue by alonm-upstream** [Wandalen/wretry.action#150]
Hey, i am using the Wandalen/wretry.action@v3.1.0 action and i have an issue where we push docker images to 2 different repositories, and we have an issue with just one repository and we want to implement the retry only for this one. 
We push to 2 repositories using this configuration:

```
  build_and_upload_image:
    name: build_and_upload_image
    timeout-minutes: 60
    needs: release_drafter_publish
    if: always()
    runs-on: ubuntu-latest
    env:
      IMAGE_VERSION: ${{ needs.release_drafter_publish.outputs.version }}
    strategy:
      matrix:
        mode: [repository_A, repository_B]
    steps: ...
```

And we have an issue that when the matrix mode is repository_A and the retry get canceled (as the condition is ${{ failure() && (matrix.mode == 'repository_B') }}), the post retry action tries to run either way and failes. 
Can you add a fix that the condition for the main action will apply to the post action? so when the main will not run the post will not run as well.

(For some reason the post tries to push the image and acts the same as the main action)
Thank you!

![Screenshot 2024-04-04 at 11 26 47](https://github.com/Wandalen/wretry.action/assets/135518307/78990b69-bbff-4053-90b3-c661023e28e2)
