### ISSUE TITLE
feature: handle actions with conditions

### ISSUE THREAD

**Issue by dmvict** [Wandalen/wretry.action#16]
The current version of action (`0.2.7`) ignores the conditions in external actions. 
It is better to add the new feature to handle conditions. 

An example of action with condition in file `action.yml`. Action `setup-node@2.4.0`:
```yaml
runs:
  using: 'node12'
  main: 'dist/setup/index.js'
  post: 'dist/cache-save/index.js'
  post-if: success()
```
