### ISSUE TITLE
'Runner "composite" does not implemented' when trying to wrap pre-commit's action

### ISSUE THREAD

**Issue by mikeage** [Wandalen/wretry.action#164]
I tried using wretry.action to wrap pre-commit's (maintainance only now) action, and it's failing with this error on the pre step (it doesn't even clone):

```
Run Wandalen/wretry.action@master
Run Wandalen/wretry.action@v3.5.0_js_action
Error: Runner "composite" does not implemented.
Please, search/open a related issue.
```

Here's a link to a failure:  
 https://github.com/mikeage/pre-commit_retry-test/actions/runs/9219438877/job/25364592211
Here's the job before, where it worked: https://github.com/mikeage/pre-commit_retry-test/actions/runs/9219409909
And here's a repo with a minimal example: https://github.com/mikeage/pre-commit_retry-test

```yaml
---
# yamllint disable rule:line-length
name: pre-commit

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - main

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Wandalen/wretry.action@master
        with:
          action: pre-commit/action@v3.0.1
```
