### ISSUE TITLE
Command to run before retry

### ISSUE THREAD

**Issue by Vampire** [Wandalen/wretry.action#165]
I was considering `nick-fields/retry` and this action for doing a run step retry.
From what I have read I prefer this action as it also supports other actions for the case I need it.
But there is one feature the other action has, that is missing here and might be helpful.
You can specify a command that is executed before a retry is tried.
This can for example be used to clean up the state before doing the retry.
Would be nice if you could add a similar or same possibility.

**Comment by dmvict** [comment]
Hello @Vampire 

Thank you for the issue. I think it is possible to add the feature. I'm too busy at the moment and cannot guarantee fast delivery. 

For now I may give you a quick solution. It's using of extended shell script. Here is a page on [`StackOverflow`](https://stackoverflow.com/questions/26675681/how-to-check-the-exit-status-using-an-if-statement).

**Comment by Vampire** [comment]
I don't see how that applies.
It might in the narrow case when you use `command` if you add the cleanup to the end of the script.
But if you run an arbitrary other action, this cannot work.

I don't need fast delivery for this, I don't need it right now.
Just thought this will for sure come in handy in the future so thought I request it that it is maybe there when I actually need it. :-)

**Comment by Vampire** [comment]
Btw. you should imho NOT call it something with or similar to "cleanup".
It can also be used for other purposes, for example logging a warning to GHA when a retry happened.

**Comment by dezren39** [comment]
i would appreciate this feature, my issue is i need to run a `git pull` between each retry

**Comment by dmvict** [comment]
Hello @Vampire and @dezren39 

You could try new version. It has option `pre_retry_command` that executes a command between retries. 

Please, give a feedback or close issue if all is OK.

**Comment by Vampire** [comment]
Seems to not work properly: https://github.com/jEdit-editor/jEdit-test/actions/runs/11645410372/job/32428416916
With
```
      uses: 'Wandalen/wretry.action/main@v3'
      with:
        command: 'echo Executing ${{ runner.temp }}/innosetup-6.3.3.exe && false'
        pre_retry_command: 'echo Reexecuting ${{ runner.temp }}/innosetup-6.3.3.exe'
        attempt_limit: '3'
        attempt_delay: '1000'
```
it says
```
Executing /home/runner/work/_temp/innosetup-6.3.3.exe
Executing /home/runner/work/_temp/innosetup-6.3.3.exe
Executing /home/runner/work/_temp/innosetup-6.3.3.exe
Error: Process returned exit code 1
Launched as "bash --noprofile --norc -eo pipefail /home/runner/work/_actions/Wandalen/wretry.action/v3.7.0_js_action/src/script.sh"
```
