### ISSUE TITLE
Take action string and inputs from another step

### ISSUE THREAD

**Issue by Vampire** [Wandalen/wretry.action#166]
I have no idea whether it is possible, but it would be nice if you could take the action string and input map from another step in the workflow.

I'm usually using typesafegithub/github-workflows-kt for writing the workflow files.

If you use this action you loose the type-safety and guidance of the library when writing the workflow file.

It would be nice if I could do something like:
```kotlin
val setupJava11 = uses(
    name = "Setup Java 11 Template",
    action = SetupJava(
        javaVersion = "11",
        distribution = Temurin
    ),
    condition = "false"
)
uses(
    name = "Setup Java 11",
    action = WretryAction(
        step = setupJava11.id
    )
)
```
which then results in
```yaml
- id: 'step-5'
  name: 'Setup Java 11 Template'
  uses: 'actions/setup-java@v4'
  with:
    java-version: '11'
    distribution: 'temurin'
  if: 'false'
- id: 'step-6'
  name: 'Setup Java 11'
  uses: 'Wandalen/wretry.action@v3'
  with:
    step: 'step-5'
```
and then your action figures out the `action` and `with` values from the other step. :-)
