### ISSUE TITLE
Retry_condition - composed condition not working?

### ISSUE THREAD

**Issue by tiagogameiro-diconium** [Wandalen/wretry.action#176]
Hi there, I am facing an issue when trying to use a composed condition on the `retry_condition` with `command`.

Here's an example:

Working scenario (only a single condition):

      - name: Step 1
        uses: Wandalen/wretry.action@8ceaefd717b7cdae4f2637f9a433242ade421a0a
        with:
          command: |
            chmod +x .github/scripts/test.sh
            .github/scripts/test.sh
          retry_condition: steps._this.outputs.status != 'FAILED'
          attempt_limit: 10
          attempt_delay: 2000

Non-Working scenario (composed condition):

      - name: Step 1
        uses: Wandalen/wretry.action@8ceaefd717b7cdae4f2637f9a433242ade421a0a
        with:
          command: |
            chmod +x .github/scripts/test.sh
            .github/scripts/test.sh
          retry_condition: steps._this.outputs.status != 'FAILED' && steps._this.outputs.status != 'WARN'
          attempt_limit: 10
          attempt_delay: 2000

in the scenario that works, the retries are interrupted when the status is FAILED, as expected.
My goal however, is that the retries are interrupted if the status is either FAILED or WARN, hence the composed condition, but it seems its not evaluating correctly the condition because it still retries the 10 times.

For reference, here's my test.sh script:

```
echo "Running check..."
echo "status=FAILED" >> "${GITHUB_OUTPUT}"
exit 1
```
Do you have any idea? Thanks in advance

**Comment by dmvict** [comment]
Hello @tiagogameiro-diconium 

Thank you for your issue. I'll check it a bit later.

**Comment by dmvict** [comment]
Hello @tiagogameiro-diconium 

I've released new version of action. It has some fixes for the case that you've described here. 

The reason of issue is in the library that performs expressions parsing and evaluating. I've described the issue and solution in last block of the [paragraph](https://github.com/Wandalen/wretry.action?tab=readme-ov-file#retry_condition).

Unfortunately I can't completely update the library to have expected behavior. So, please, try new version with the updated condition:
 
```yaml
  - name: Step 1
    uses: Wandalen/wretry.action@8ceaefd717b7cdae4f2637f9a433242ade421a0a
    with:
      command: |
        chmod +x .github/scripts/test.sh
        .github/scripts/test.sh
      retry_condition: (steps._this.outputs.status != 'FAILED') && (steps._this.outputs.status != 'WARN')
      attempt_limit: 10
      attempt_delay: 2000
```
