### ISSUE TITLE
post stage not run

### ISSUE THREAD

**Issue by dud225** [Wandalen/wretry.action#184]
Hello

When running the following workflow:
```
name: test

on:
  push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: Wandalen/wretry.action@v3.8.0
        with:
          action: jdx/mise-action@v2
          attempt_limit: 5
          attempt_delay: 2000
```

I notice that mise-action's post stage isn't run:

![Image](https://github.com/user-attachments/assets/048405e5-1f23-40b7-b256-d2f76a7f1735)

mise-action's post stage: https://github.com/jdx/mise-action/blob/5083fe46898c414b2475087cc79da59e7da859e8/action.yml#L62-L63

When shelving wretry.action the post action is correctly run: 

![Image](https://github.com/user-attachments/assets/9e19ab04-d1ab-4170-8b16-c6b1a0892363)
