### ISSUE TITLE
Troubles with running the local composite actions

### ISSUE THREAD

**Issue by MichalMucek** [Wandalen/wretry.action#186]
I'm having trouble running the local actions. I noticed that the pre-step of the wretry.action is looking for the target action, so I figured I'll be stashing it on the hosting machine, but then I'm getting this error - `Expects strings as path arguments, but #2 argument is Undefined`. I verified that the provided value is correct; the logs of wretry.action are showing it as expected. Below is an example of how I fail to do it.

```yml
jobs:
  prepare-stash:
    name: Prepare Repository Actions Stash on Linux
    runs-on: Linux-machine
    outputs:
      stash_path: ${{ steps.put-to-stash.outputs.stash_path }}
    steps:
      - uses: actions/checkout@v4
        with:
          clean: true
          sparse-checkout: .github/actions/put-repository-actions-into-stash-linux

      - name: Put Repository Actions into Stash (Linux)
        id: put-to-stash
        # Checkout the .github/actions and copy them to the stash folder
        uses: ./.github/actions/put-repository-actions-into-stash-linux
        with:
          stash-folder-base-path-linux: ${{ vars.WORKFLOW_EXECUTION_STASH_FOLDER_BASE_PATH_LINUX}}

  build-release:
    name: Build  Release
    needs: prepare-stash
    runs-on: XGRJ63
    steps:
      - uses: actions/checkout@v4
        with:
          clean: true

      - name: Build Solution
        uses: Wandalen/wretry.action@v3
        with:
          attempt_limit: 3
          # Example stash_path: /home/user1/GitHub_Runners/.stash/pull-request/12345
          action: '${{ needs.prepare-stash.outputs.stash_path }}/.github/actions/build'
          with: |
            configuration: 'Release'
```
