### ISSUE TITLE
Input does not meet YAML 1.2 "Core Schema

### ISSUE THREAD

**Issue by PrimalPimmy** [Wandalen/wretry.action#42]
https://github.com/PrimalPimmy/tremor-runtime/runs/6396863368?check_suite_focus=true

Getting this error when running the workflow. My inputs are:

```
        - name: Publish tremor-script to crates.io
          uses: Wandalen/wretry.action@v1.0.11
          with:
            action: katyo/publish-crates@v1
            with: |
              path: './tremor-script'
              args: --no-verify
              dry-run: true 
            attempt_limit: 6
            attempt_delay: 10000
```

I can't point out what's wrong here, seems like a configuration issue here

**Comment by dmvict** [comment]
> 

Hello, @PrimalPimmy 

Thank you for your issue. We'll investigate and solve this bug. Now, our command have a lot of work so, we'll solve bug a little later. Thank you for your patience.

**Comment by ermirizio** [comment]
Hi! Experiencing same error here while trying to retru on docker/buil-push-action@v3

```
      - name: retry docker build
        uses: Wandalen/wretry.action@v1.0.19
        with:
          action: docker/build-push-action@v3
          with: |
            context: .
            push: false
            tags: app:latest
          attempt_limit: 3
          attempt_delay: 2000
```
Can't share the logs since is a private repo, here is a picture:

![image](https://user-images.githubusercontent.com/35462288/169161119-64b3cd0c-c14c-47f9-a513-24539458284a.png)
