### ISSUE TITLE
Error: Cannot read property 'trim' of undefined

### ISSUE THREAD

**Issue by beyarkay** [Wandalen/wretry.action#64]
Hey!

Thanks for the action, it looks great. I'm trying to use it for a rather complicated use-case, and am getting the error

```
Error: Cannot read property 'trim' of undefined
```

Which comes from this line in your source code:  https://github.com/Wandalen/wretry.action/blob/master/src/Common.js#L188:

```js
  function jobContextGet()
  {
    const context = Object.create( null );

    if( dockerExists() )
    {
      const containersIds = execSyncNonThrowing( 'docker ps --all --filter status=running --no-trunc --format "{{.ID}}"' );
      const ids = _.strSplit({ src : containersIds.toString(), delimeter : '\n', preservingEmpty : 0 });
      context.container = Object.create( null );
      context.services = Object.create( null );
      for( let i = 0 ; i < ids.length ; i++ )
      {
        const output = execSyncNonThrowing( `docker inspect ${ ids[ i ].trim() }` );  // <---- error here
        const parsed = JSON.parse( output.toString() );
        if( !context.container.network )
        context.container.network = parsed[ 0 ].HostConfig.NetworkMode;

        const service = Object.create( null );
        service.id = parsed[ 0 ].Id;
        service.ports = Object.create( null );
        for( let key in parsed[ 0 ].NetworkSettings.Ports )
        if( parsed[ 0 ].NetworkSettings.Ports[ key ] !== null )
        service.ports[ key.split( '/' )[ 0 ] ] = parsed[ 0 ].NetworkSettings.Ports[ key ][ 0 ].HostPort;
        service.network = context.container.network;

        context.services[ parsed[ 0 ].Args[ 0 ] ] = service;
      }
    }
```

But I've got no clue about what's happening when it comes to docker containers, so unfortunately this is an issue and not a PR.

Here's the commit where I modified the existing workflow to use your action: https://github.com/beyarkay/eskom-calendar-dev/commit/77bf6dcf4aca9aaf6994ed874cea47e7eddf6fdc

Here's the lines in the github workflow files where I'm using your action: https://github.com/beyarkay/eskom-calendar-dev/blob/main/.github/workflows/publish-calendars.yaml#L59-L111

Here's the run where I got the error: https://github.com/beyarkay/eskom-calendar-dev/actions/runs/3157204705/jobs/5137784537#step:10:56

I have a feeling that, because I've embedded a string inside the embeded string (see the [`body`](https://github.com/beyarkay/eskom-calendar-dev/blob/main/.github/workflows/publish-calendars.yaml#L72) key and value in my action) that yaml might be getting confused? But this doesn't really match with the error as far as I can see.

**Comment by beyarkay** [comment]
Okay so I changed the multi-line string `body` to a single line, and it looks like [the resulting step](https://github.com/beyarkay/eskom-calendar-dev/actions/runs/3157469513/jobs/5138378759) is working as expected.

I'm not entirely sure what to do though, because that multiline string is pretty essential.

**Comment by beyarkay** [comment]
Ah sorry you're right, it's my test environment for eskom-calendar which is the production environment. I'll send through snippets now

**Comment by beyarkay** [comment]
Here's the workflow that succeeds (maybe because `body` isn't a multiline string?)

```yaml
name: Build and Publish Calendars

on:
  push:
    branches: [ "main" ]
    paths:
      - 'manually_specified.yaml'
      - 'src/*.rs'
      - 'src/*.py'
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-publish-calendars:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

    - name: Pip install requirements
      uses: BSFishy/pip-action@v1
      with:
        requirements: requirements.txt

    - name: Cargo build
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --release

    - name: Cargo run
      uses: actions-rs/cargo@v1
      with:
        command: run
        args: --release

    - name: Write current time stamp to GH variable
      id: date
      run: echo "::set-output name=datetime::$(date +'%Y-%m-%dT%H:%M:%S')"

    - name: List all calendars to GH variable
      run: echo "::set-output name=LS_CALENDARS::$(ls calendars/* | xargs echo | sed 's/ /,/g')"
      id: LS-CALENDARS

      # =========================
      # wretry.action STARTS HERE
      # =========================

    - name: Update latest release with new calendars, retrying if needed
      uses: Wandalen/wretry.action@v1.0.11
      with:
        attempt_limit: 5    # Retry up to 5 times
        attempt_delay: 5000 # Wait 5 seconds between attempts
        action: beyarkay/update-existing-release@master
        with: |
          token: ${{ secrets.GH_ACTIONS_PAT }}
          release: Latest Eskom Loadshedding Calendars
          updateTag: true
          tag: latest
          replace: true
          body: "This is the body"
          files: ${{ steps.LS-CALENDARS.outputs.LS_CALENDARS }}
```

And here's the action that fails, maybe because of the multiline string:


```yaml
name: Build and Publish Calendars

on:
  push:
    branches: [ "main" ]
    paths:
      - 'manually_specified.yaml'
      - 'src/*.rs'
      - 'src/*.py'
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-publish-calendars:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

    - name: Pip install requirements
      uses: BSFishy/pip-action@v1
      with:
        requirements: requirements.txt

    - name: Cargo build
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --release

    - name: Cargo run
      uses: actions-rs/cargo@v1
      with:
        command: run
        args: --release

    - name: Write current time stamp to GH variable
      id: date
      run: echo "::set-output name=datetime::$(date +'%Y-%m-%dT%H:%M:%S')"

    - name: List all calendars to GH variable
      run: echo "::set-output name=LS_CALENDARS::$(ls calendars/* | xargs echo | sed 's/ /,/g')"
      id: LS-CALENDARS

    - name: Update latest release with new calendars, retrying if needed
      uses: Wandalen/wretry.action@v1.0.11
      with:
        attempt_limit: 5    # Retry up to 5 times
        attempt_delay: 5000 # Wait 5 seconds between attempts
        action: beyarkay/update-existing-release@master
        with: |
          token: ${{ secrets.GH_ACTIONS_PAT }}
          release: Latest Eskom Loadshedding Calendars
          updateTag: true
          tag: latest
          replace: true
          files: ${{ steps.LS-CALENDARS.outputs.LS_CALENDARS }}
          body: "# To get your load shedding schedule in your calendar:
            1. Scroll down to the blue links under `Assets`:
            ![Assets image](https://github.com/beyarkay/eskom-calendar/blob/main/imgs/assets.png)
            2. Find the `ics` calendar file corresponding to your area (use ctrl-f to search quickly).
            3. Right-click on the file and copy the link:
            ![Right click and copy image](https://github.com/beyarkay/eskom-calendar/blob/main/imgs/copy-link.png)
            4. Open your calendar app (Google Calendar, Outlook, Apple Calendar, etc)
            5. Paste the calendar link in your app's `subscribe to calendar` option.
            | [Google Calendar](https://calendar.google.com/calendar/u/0/r/settings/addbyurl)  | [Outlook](https://outlook.office.com/calendar/addcalendar) | [Apple Calendar](https://support.apple.com/en-za/guide/calendar/icl1022/mac) |
            | ----------------- | --------------- | --------------- |
            | ![google calendar subscription image](https://github.com/beyarkay/eskom-calendar/blob/main/imgs/gcal.png) | ![outlook subscripition image](https://github.com/beyarkay/eskom-calendar/blob/main/imgs/outlook.png) | ![apple calendar subscription image](https://github.com/beyarkay/eskom-calendar/blob/main/imgs/ical.png) |
            That's it! 
            ### Details
            Now you've got loadshedding warnings in your calendar that tell you if the power will be off or not. This is better than apps like EskomSePush because it combines what area you're in with your area's loadshedding schedule. You'll only be notified if
            1. there's national loadshedding announced by Eskom *and*
            2. your area has loadshedding scheduled for that time.
            ### Developers
            There's also a machine-friendly csv file that contains loadshedding information. Have a look at the [`README.md`](https://github.com/beyarkay/eskom-calendar/tree/latest) for ideas!
            Last updated: ${{ steps.date.outputs.datetime }} UTC"
```

**Comment by dmvict** [comment]
@beyarkay 

It is restriction of the action. Each line of the field `with`  is interpreted as the pair `key-value` (see description of the field [`with`](https://github.com/Wandalen/wretry.action#with)).
Now you can use only single-line `value`. 

I will try to extend action to handle such cases correctly.

**Comment by beyarkay** [comment]
Hmm okay, thanks for trying to fix it!

**Comment by dmvict** [comment]
Hello, @beyarkay 

I've fixed the problem with multiline strings in #65. 
The new behavior is tested by the new tests.
Also, I manually test it in a test repository. 

Code snippet: 
```yaml
      - uses : dmvict/wretry.action@fix
        with:
          action: dmvict/test.action@multiline_option
          with: |
            multiline: |
              one
              two
            string: |
          attempt_limit: 3
          attempt_delay: 2000
```

And the action works as I expected:
![зображення](https://user-images.githubusercontent.com/47529590/193272856-d1c812ba-aa9c-4f98-baa5-6da9957241ab.png)

Please, use action [`Wandalen/wretry.action@master`](https://github.com/Wandalen/wretry.action) when PR #65 will be merged. 
Do not use the `dmvict/wretry.action@fix` because, after the merge the branch `fix` will be removed.

**Comment by beyarkay** [comment]
Thanks! any idea when #65 will be merged?

**Comment by dmvict** [comment]
I think it will be soon. I will report to the owner [Wandalen](https://github.com/Wandalen) that I opened PR with the fix.

**Comment by dmvict** [comment]
The PR #65 was merged. 
You can try to use new version.

**Comment by beyarkay** [comment]
I've changed my workflow to use 1.0.28, but now I'm getting the error: `Error: Expects non-primitive`.

Any idea what's causing this?

**Comment by dmvict** [comment]
I think you are using invalid formatting. 

Simplified example:
```yaml
option: | 
  first string 
  second string 
``` 
It is important to write vertical bare in declaration of multiline option and use indentation for each string in multiline option.

**Comment by beyarkay** [comment]
I can't see any errors in the formatting, but maybe I'm missing something? [I uploaded the YAML here](https://codebeautify.org/yaml-validator/y2223e7ec) and it all seems to be valid. Here's the full file again:

```yaml
name: Build and Publish Calendars

on:
  push:
    branches: [ "main" ]
    paths:
      - 'manually_specified.yaml'
      - 'src/*.rs'
      - 'src/*.py'
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-publish-calendars:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

    - name: Pip install requirements
      uses: BSFishy/pip-action@v1
      with:
        requirements: requirements.txt

    - name: Cargo build
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --release

    - name: Cargo run
      uses: actions-rs/cargo@v1
      with:
        command: run
        args: --release

    - name: Write current time stamp to GH variable
      id: date
      run: echo "::set-output name=datetime::$(date +'%Y-%m-%dT%H:%M:%S')"

    - name: List all calendars to GH variable
      run: echo "::set-output name=LS_CALENDARS::$(ls calendars/* | xargs echo | sed 's/ /,/g')"
      id: LS-CALENDARS


    - name: Update latest release with new calendars, retrying if needed
      uses: Wandalen/wretry.action@v1.0.28
      with:
        attempt_limit: 5    # Retry up to 5 times
        attempt_delay: 5000 # Wait 5 seconds between attempts
        action: beyarkay/update-existing-release@master
        with: |
          token: ${{ secrets.GH_ACTIONS_PAT }}
          release: Latest Eskom Loadshedding Calendars
          updateTag: true
          tag: latest
          replace: true
          files: ${{ steps.LS-CALENDARS.outputs.LS_CALENDARS }}
          body: "# To get your load shedding schedule in your calendar:
            1. Scroll down to the blue links under `Assets`:
            ![Assets image](https://github.com/beyarkay/eskom-calendar/blob/main/imgs/assets.png)
            2. Find the `ics` calendar file corresponding to your area (use ctrl-f to search quickly).
            3. Right-click on the file and copy the link:
            ![Right click and copy image](https://github.com/beyarkay/eskom-calendar/blob/main/imgs/copy-link.png)
            4. Open your calendar app (Google Calendar, Outlook, Apple Calendar, etc).
            5. Paste the calendar link in your app's `subscribe to calendar` option:
            | [Google Calendar](https://calendar.google.com/calendar/u/0/r/settings/addbyurl)  | [Outlook](https://outlook.office.com/calendar/addcalendar) | [Apple Calendar](https://support.apple.com/en-za/guide/calendar/icl1022/mac) |
            | ----------------- | --------------- | --------------- |
            | ![google calendar subscription image](https://github.com/beyarkay/eskom-calendar/blob/main/imgs/gcal.png) | ![outlook subscripition image](https://github.com/beyarkay/eskom-calendar/blob/main/imgs/outlook.png) | ![apple calendar subscription image](https://github.com/beyarkay/eskom-calendar/blob/main/imgs/ical.png) |
            That's it!
            ### Details
            Now you've got loadshedding warnings in your calendar that tell you if the power will be off or not. This is better than apps like EskomSePush because it combines what area you're in with your area's loadshedding schedule. You'll only be notified if
            1. there's national loadshedding announced by Eskom *and*
            2. your area has loadshedding scheduled for that time.
            ### Developers
            There's also a machine-friendly csv file that contains loadshedding information. Have a look at the [`README.md`](https://github.com/beyarkay/eskom-calendar/tree/latest) for ideas!
            Last updated: ${{ steps.date.outputs.datetime }} UTC"
```

**Comment by dmvict** [comment]
Sorry, I had some important tasks. 

The file is correct. The simplest parser that I implemented for the multiline strings uses vertical bar as begin token and indentations as continuation. 

Please, replace the action with this code:
```yaml
    - name: Update latest release with new calendars, retrying if needed
      uses: Wandalen/wretry.action@v1.0.28
      with:
        attempt_limit: 5    # Retry up to 5 times
        attempt_delay: 5000 # Wait 5 seconds between attempts
        action: beyarkay/update-existing-release@master
        with: |
          token: ${{ secrets.GH_ACTIONS_PAT }}
          release: Latest Eskom Loadshedding Calendars
          updateTag: true
          tag: latest
          replace: true
          files: ${{ steps.LS-CALENDARS.outputs.LS_CALENDARS }}
          body: |
            # To get your load shedding schedule in your calendar:
            1. Scroll down to the blue links under `Assets`:
            ![Assets image](https://github.com/beyarkay/eskom-calendar/blob/main/imgs/assets.png)
            2. Find the `ics` calendar file corresponding to your area (use ctrl-f to search quickly).
            3. Right-click on the file and copy the link:
            ![Right click and copy image](https://github.com/beyarkay/eskom-calendar/blob/main/imgs/copy-link.png)
            4. Open your calendar app (Google Calendar, Outlook, Apple Calendar, etc).
            5. Paste the calendar link in your app's `subscribe to calendar` option:
            | [Google Calendar](https://calendar.google.com/calendar/u/0/r/settings/addbyurl)  | [Outlook](https://outlook.office.com/calendar/addcalendar) | [Apple Calendar](https://support.apple.com/en-za/guide/calendar/icl1022/mac) |
            | ----------------- | --------------- | --------------- |
            | ![google calendar subscription image](https://github.com/beyarkay/eskom-calendar/blob/main/imgs/gcal.png) | ![outlook subscripition image](https://github.com/beyarkay/eskom-calendar/blob/main/imgs/outlook.png) | ![apple calendar subscription image](https://github.com/beyarkay/eskom-calendar/blob/main/imgs/ical.png) |
            That's it!
            ### Details
            Now you've got loadshedding warnings in your calendar that tell you if the power will be off or not. This is better than apps like EskomSePush because it combines what area you're in with your area's loadshedding schedule. You'll only be notified if
            1. there's national loadshedding announced by Eskom *and*
            2. your area has loadshedding scheduled for that time.
            ### Developers
            There's also a machine-friendly csv file that contains loadshedding information. Have a look at the [`README.md`](https://github.com/beyarkay/eskom-calendar/tree/latest) for ideas!
            Last updated: ${{ steps.date.outputs.datetime }} UTC
```

**Comment by beyarkay** [comment]
Thanks! Trying this out now...

**Comment by dmvict** [comment]
Hello, @beyarkay 

This PR https://github.com/Wandalen/wretry.action/pull/86 should solve the problem with skipping of empty strings.

**Comment by dmvict** [comment]
Hello, @beyarkay 

The new version is released. Please, try version `v1.2.0` and give me a feedback.

**Comment by beyarkay** [comment]
Thanks! Will do when I get a minute

**Comment by dominicmh** [comment]
@beyarkay, did this fix the issue for you?
I noticed that accessing GitHub Actions secrets resulted in the mentioned `Error: Expects non-primitive`:

```yaml
- uses: Wandalen/wretry.action@master
  with:
    action: action/foo@1.2.3
    with: |
      architecture: ${{ secrets.BAR }}
```
