### ISSUE TITLE
Support multiple lines `command`

### ISSUE THREAD

**Issue by Hongbo-Miao** [Wandalen/wretry.action#79]
The original `run` supports multiple lines such as

```yml
        run: |
          xcodebuild build-for-testing \
            -project HMMobile.xcodeproj \
            -scheme HMMobile \
            -destination "platform=iOS Simulator,name=iPhone 14 Pro,OS=16.1"
```

However, for 

```yml
      - uses: wandalen/wretry.action@v1.0.36
        with:
          command: |
            xcodebuild test-without-building \
              -project HMMobile.xcodeproj \
              -scheme HMMobile \
              -destination "platform=iOS Simulator,name=iPhone 14 Pro,OS=16.1"
          attempt_limit: 3
          attempt_delay: 2000
```

It will only run whatever in first line which is `xcodebuild test-without-building \`

Here is the GitHub Action log:

```sh
Command line invocation:
    /Applications/Xcode_14.1.app/Contents/Developer/usr/bin/xcodebuild test-without-building

User defaults from command line:
    IDEPackageSupportUseBuiltinSCM = YES

2022-12-31 12:43:39.234 xcodebuild[3246:15150] Writing error result bundle to /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/ResultBundle_2022-31-12_12-43-0039.xcresult
xcodebuild: error: The test action requires that the name of a scheme in the project is provided using the "-scheme" option. The "-list" option can be used to find the names of the schemes in the project.
Command line invocation:
    /Applications/Xcode_14.1.app/Contents/Developer/usr/bin/xcodebuild test-without-building

User defaults from command line:
    IDEPackageSupportUseBuiltinSCM = YES

2022-12-31 12:43:44.530 xcodebuild[3417:15606] Writing error result bundle to /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/ResultBundle_2022-31-12_12-43-0044.xcresult
xcodebuild: error: The test action requires that the name of a scheme in the project is provided using the "-scheme" option. The "-list" option can be used to find the names of the schemes in the project.
Command line invocation:
    /Applications/Xcode_14.1.app/Contents/Developer/usr/bin/xcodebuild test-without-building

User defaults from command line:
    IDEPackageSupportUseBuiltinSCM = YES

2022-12-31 12:43:49.909 xcodebuild[3453:15777] Writing error result bundle to /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/ResultBundle_2022-31-12_12-43-0049.xcresult
xcodebuild: error: The test action requires that the name of a scheme in the project is provided using the "-scheme" option. The "-list" option can be used to find the names of the schemes in the project.
Error: Process returned exit code 65
Launched as "xcodebuild test-without-building \"
Launched at "/Users/runner/work/hongbomiao.com/hongbomiao.com/mobile-ios"
Attempts exhausted, made 3 attempts :
Attempt #1 started at : 12:43:35 GMT+0000 (Coordinated Universal Time)
Attempt #2 started at : 12:43:42 GMT+0000 (Coordinated Universal Time)
Attempt #3 started at : 12:43:47 GMT+0000 (Coordinated Universal Time)
```

It works after I change to

```yml
        uses: wandalen/wretry.action@v1.0.36
        with:
          command: |
            xcodebuild test-without-building -project HMMobile.xcodeproj -scheme HMMobile -destination "platform=iOS Simulator,name=iPhone 14 Pro,OS=16.1"
          attempt_limit: 3
          attempt_delay: 2000
```

It would be nice to have support for multiple lines command, thanks! 😃
