### ISSUE TITLE
Unable to access the outputs of another action

### ISSUE THREAD

**Issue by karadikidd** [Wandalen/wretry.action#84]
Hello,

I'm running an action which has several `outputs`.
When using the said action directly, all outputs are available for other jobs, however, when running the said action using the `wretry.action` those outputs are not exposed.

An example code block:
```
jobs:
  do-some-work:
    if: always()
    name: Some name...
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.do-something.outputs.output1 }}
      output2: ${{ steps.do-something.outputs.output2 }}
      output3: ${{ steps.do-something.outputs.output3 }}
  steps:
    - name: Do something
        id: do-something
        uses: Wandalen/wretry.action@master
        with:
          attempt_limit: 3
          attempt_delay: 5000
          action: repo/some-action@main
          with: |
            option1: foo
            option2: bar
            option3: ...
            option4: ...
```

Was wondering if it is possible to access the `outputs` of other actions and if so any guidelines would be greatly appreciated.
